### ISSUE TITLE
Receive Hearts One By One Function Not Working on NOX or Different Android Devices

### ISSUE THREAD

**Issue by edstewbob** [r2-studio/robotmon-scripts#512] opened 2024-02-27 02:08 UTC
On Pixel 4 Android 13 I installed the current Robotmon and script release 65 with settings including Receive All Hearts, Receive Hearts One By One, and Auto Send Hearts along with other settings I had been using successfully for months on script 58 on a 32 bit NOX 7 setup. Everything works fine on release 65 except Receive Hearts One By One. The Mailbox is opened which has a large list of hearts to check and receive the 200 coin gift if received within 1 hour of receipt. Instead of receiving the gifts one by one the window is just closed and the game proceeds leaving me to pause the game and manually receive the inbox hearts and coins. I tried the same thing on a Samsung Tablet running Android 14 with the same results.
If I turn off Receive Hearts One By One and leave Receive All Hearts on, the claim all hearts function does empty the inbox of hearts but the 200 coin bonus is not received for each entry and the sender of the heart does not receive a heart in return at that time. With large inbox counts of 50-100 per hour this represents a significant amount of additional coins that may be lost without manually receiving the inbox entries one by one within the hour.

**Comment by mcs** [comment] 2024-02-27 04:31
Hello, do you use "Special Screen Ratio" and do you start the script **after** the game has been fully started? If so, could you please upload a short video with open log window and enabled additional debug logs which demonstrates the issue? `Debug logs` can be enabled within the hidden [devloper options](https://github.com/mcs/robotmon-scripts/tree/main/scripts/com.r2studio.TsumBeta#developer-options).

**Comment by edstewbob** [comment] 2024-02-27 04:59
I don't use Special Screen Ratio and I always start the script before the game is started and the script starts the execution of the game. Attached are my settings,
![Screenshot_20240226-234036](https://github.com/r2-studio/robotmon-scripts/assets/14189782/a96eaca9-f309-4b80-b556-d134d94d211f)
![Screenshot_20240226-234048](https://github.com/r2-studio/robotmon-scripts/assets/14189782/5f79535c-27f3-4416-be32-2d2344c09b5a)
![Screenshot_20240226-234057](https://github.com/r2-studio/robotmon-scripts/assets/14189782/b777f79d-c23c-4ca5-bc2a-0aeff9f0581f)

**Comment by edstewbob** [comment] 2024-02-27 05:08
In the above settings I did activate Receive All Hearts and disabled Receive Hearts One By One that is currently running on the Samsung tablet so that the Inbox doesn't get backed up but when they are both activated the issue occurs.

**Comment by mcs** [comment] 2024-02-27 10:38
Thank you for the feedback. Could you please post a full screenshot of the
game itself created by your phone? I need to check the black bars above and
below the game screen. Ideally there is no phone info bar at the top of
buttons at the button when you create the screenshot, just the full screen
exclusively the game (Robotmon icons on the top are okay, too).

**Comment by edstewbob** [comment] 2024-02-27 18:11
I am attaching a few shots of the game in progress and a picture of the Inbox contents where Close is selected instead of selecting claim one be one to send back hearts one by one. This run has Receive Hearts One By One selected but not Receive All Hearts and you can see the Inbox beginning to build up.
![Screenshot_20240227_121449_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/b68b8dad-cefc-4d14-9ad1-e8dc0ae155f6)
![Screenshot_20240227_121100_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/3c4d234a-1372-40b0-a27b-db9ea3cd6e82)
![Screenshot_20240227_120849_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/d725b862-3cee-4245-87d4-de614bc01eb0)
![Screenshot_20240227_121536_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/aeb57e74-7808-4e69-8ea9-4c83839b8faa)
![Screenshot_20240227_121606_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/24726889-99d0-4733-8e78-28806a257f8b)
![Screenshot_20240227_121553_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/e0e0e201-bbce-4c65-a5a8-5e5529e7ea91)
![Screenshot_20240227_121545_TsumTsum](https://github.com/r2-studio/robotmon-scripts/assets/14189782/3451d31d-66dd-4ec5-bf67-50242b2232b7)

**Comment by mcs** [comment] 2024-02-27 19:11
Thanks again for the additional screenshots. I now realize that I never had any ads in my mailbox due to my location which would have made testing and reproducing the issue quite hard. But finally I could make it look like on your screenshot by "moving to Los Angeles".

What worked immediately for me as a quick solution was enbling this setting:
![grafik](https://github.com/r2-studio/robotmon-scripts/assets/33131/1eba1035-9bd2-4345-8882-e51629e127a4)

Regarding ad detection and handling, I might change the detection in a later version as v66 is already submitted as Pull Request #513.

**Comment by edstewbob** [comment] 2024-02-27 19:30
Awesome! That works fine. Thank you very much for your quick solution! The reason I think we didn't see it on an older version is that it is running in NOX on a PC and that never gets the option to view an add to win rubies.

**Comment by Sean-Hsueh** [comment] 2024-03-30 01:17
Closing the case as it is resolved :)

**Closed by Sean-Hsueh** 2024-03-30 01:17 UTC
